import { ItemDetails, ShoppingItem } from "@/types/shopping";
import { CustomerReviewsResponse } from "@/types/customer";

export const mockShoppingItemsData: ShoppingItem[] = [
  {
    id: "1",
    imageAlt: "Handwoven Scarf",
    imageUrl: "/images/item-mock/item1.webp",
    productName: "Handwoven Scarf",
    sellerName: "ArtisanName",
    price: "$45.00",
    rating: 4.8,
    isAddedToCart: false,
  },
  {
    id: "2",
    imageAlt: "Ceramic Mug Set",
    imageUrl: "/images/item-mock/item2.webp",
    productName: "Ceramic Mug Set",
    sellerName: "PotteryMaster",
    price: "$32.00",
    rating: 4.9,
    isAddedToCart: false,
  },
  {
    id: "3",
    imageAlt: "Wooden Jewelry Box",
    imageUrl: "/images/item-mock/item3.webp",
    productName: "Wooden Jewelry Box",
    sellerName: "WoodCrafter",
    price: "$78.00",
    rating: 4.7,
    isAddedToCart: true,
  },
  {
    id: "4",
    imageAlt: "Knitted Blanket",
    imageUrl: "/images/item-mock/item4.webp",
    productName: "Knitted Blanket",
    sellerName: "YarnArtist",
    price: "$95.00",
    rating: 5.0,
    isAddedToCart: false,
  },
  {
    id: "5",
    imageAlt: "Handmade Ceramic Vase",
    imageUrl: "/images/item-mock/item5.webp",
    productName: "Handmade Ceramic Vase",
    sellerName: "ClayArtisan",
    price: "$50.00",
    rating: 4.6,
    isAddedToCart: false,
  },
  {
    id: "6",
    imageAlt: "Woven Basket",
    imageUrl: "/images/item-mock/item11.webp",
    productName: "Woven Basket",
    sellerName: "BasketWeaver",
    price: "$40.00",
    rating: 4.4,
    isAddedToCart: false,
  },
  {
    id: "7",
    imageAlt: "Handcrafted Wooden Bowl",
    imageUrl: "/images/item-mock/item12.webp",
    productName: "Handcrafted Wooden Bowl",
    sellerName: "WoodArtisan",
    price: "$60.00",
    rating: 4.9,
    isAddedToCart: false,
  },
  {
    id: "8",
    imageAlt: "Embroidered Cushion Cover",
    imageUrl: "/images/item-mock/item8.webp",
    productName: "Embroidered Cushion Cover",
    sellerName: "TextileArtist",
    price: "$25.00",
    rating: 4.7,
    isAddedToCart: false,
  },
  {
    id: "9",
    imageAlt: "Handmade Leather Wallet",
    imageUrl: "/images/item-mock/item9.webp",
    productName: "Handmade Leather Wallet",
    sellerName: "LeatherCraftsman",
    price: "$55.00",
    rating: 4.8,
    isAddedToCart: false,
  },
  {
    id: "10",
    imageAlt: "Ceramic Plant Pot",
    imageUrl: "/images/item-mock/item10.webp",
    productName: "Ceramic Plant Pot",
    sellerName: "PotteryStudio",
    price: "$35.00",
    rating: 4.5,
    isAddedToCart: false,
  },
];

export const mockCategoriesData = [
  "Jewelry",
  "Home Decor",
  "Clothing",
  "Art"
];

export const mockItemDetailsData: ItemDetails =
{
  id: "1",
  name: "Handmade Ceramic Coffee Mug",
  price: 28.0,
  description: "Beautiful handcrafted ceramic coffee mug made with love and attention to detail. Each piece is unique and features a smooth glaze finish. Perfect for your morning coffee or evening tea. Dishwasher and microwave safe.",
  material: "Ceramic",
  capacity: "12 oz",
  dimensions: "4\" x 4\" x 4\"",
  care: "Dishwasher Safe",
  seller: {
    name: "PotteryStudio",
    memberSince: "2019",
    rating: 4.9,
    reviews: 156,
    profileImageUrl: "/images/user_placeholder.png",
  },
  images: [
    "/images/item-mock/item1.webp",
    "/images/item-mock/item2.webp",
    "/images/item-mock/item3.webp",
    "/images/item-mock/item4.webp",
    "/images/item-mock/item5.webp",
    "/images/item-mock/item6.webp",
    "/images/item-mock/item7.webp",
    "/images/item-mock/item8.webp",
    "/images/item-mock/item9.webp",
    "/images/item-mock/item10.webp",
    "/images/item-mock/item11.webp",
    "/images/item-mock/item12.webp",
  ],
  rating: 4.3,
  reviews: 24,
  isAddedToCart: false,
};

export const mockCustomerReviewsData: CustomerReviewsResponse = {

  ratingBreakdown: {
    totalReviews: 24,
    averageRating: 4.3,
    ratingsCount: {
      1: 0,
      2: 0,
      3: 1,
      4: 4,
      5: 19,
    },
  },
  reviews: [
    {
      id: "1",
      reviewerName: "Jane Doe",
      reviewerProfileImageUrl: "/images/user_placeholder.png",
      rating: 5,
      reviewDate: "2 days ago",
      reviewText: "Absolutely love this mug! The craftsmanship is excellent and it feels perfect in my hands. The glaze is beautiful and it keeps my coffee warm. Highly recommend!",
    },
    {
      id: "2",
      reviewerName: "Mike Smith",
      reviewerProfileImageUrl: "/images/user_placeholder.png",
      rating: 5,
      reviewDate: "1 week ago",
      reviewText: "Great quality mug. Arrived quickly and was packaged very well. Perfect size for my morning coffee routine.",
    },
  ],
}
