import { ItemDetails, ShoppingItem } from "@/types/shopping";
import { CustomerReviewsResponse } from "@/types/customer";
import { CartItem } from "@/types/cart";
import { QuickStatsData, PersonalInfoData, InventoryData } from "@/types/seller";


export const mockShoppingItemsData: ShoppingItem[] = [
  {
    id: "1",
    imageAlt: "Handwoven Scarf",
    imageUrl: "/images/item-mock/item1.webp",
    productName: "Handwoven Scarf",
    sellerName: "ArtisanName",
    price: 45.00,
    rating: 4.8,
    isAddedToCart: false,
  },
  {
    id: "2",
    imageAlt: "Ceramic Mug Set",
    imageUrl: "/images/item-mock/item2.webp",
    productName: "Ceramic Mug Set",
    sellerName: "PotteryMaster",
    price: 32.00,
    rating: 4.9,
    isAddedToCart: false,
  },
  {
    id: "3",
    imageAlt: "Wooden Jewelry Box",
    imageUrl: "/images/item-mock/item3.webp",
    productName: "Wooden Jewelry Box",
    sellerName: "WoodCrafter",
    price: 78.00,
    rating: 4.7,
    isAddedToCart: true,
  },
  {
    id: "4",
    imageAlt: "Knitted Blanket",
    imageUrl: "/images/item-mock/item4.webp",
    productName: "Knitted Blanket",
    sellerName: "YarnArtist",
    price: 95.00,
    rating: 5.0,
    isAddedToCart: false,
  },
  {
    id: "5",
    imageAlt: "Handmade Ceramic Vase",
    imageUrl: "/images/item-mock/item5.webp",
    productName: "Handmade Ceramic Vase",
    sellerName: "ClayArtisan",
    price: 50.00,
    rating: 4.6,
    isAddedToCart: false,
  },
  {
    id: "6",
    imageAlt: "Woven Basket",
    imageUrl: "/images/item-mock/item11.webp",
    productName: "Woven Basket",
    sellerName: "BasketWeaver",
    price: 40.00,
    rating: 4.4,
    isAddedToCart: false,
  },
  {
    id: "7",
    imageAlt: "Handcrafted Wooden Bowl",
    imageUrl: "/images/item-mock/item12.webp",
    productName: "Handcrafted Wooden Bowl",
    sellerName: "WoodArtisan",
    price: 60.00,
    rating: 4.9,
    isAddedToCart: false,
  },
  {
    id: "8",
    imageAlt: "Embroidered Cushion Cover",
    imageUrl: "/images/item-mock/item8.webp",
    productName: "Embroidered Cushion Cover",
    sellerName: "TextileArtist",
    price: 25.00,
    rating: 4.7,
    isAddedToCart: false,
  },
  {
    id: "9",
    imageAlt: "Handmade Leather Wallet",
    imageUrl: "/images/item-mock/item9.webp",
    productName: "Handmade Leather Wallet",
    sellerName: "LeatherCraftsman",
    price: 55.00,
    rating: 4.8,
    isAddedToCart: false,
  },
  {
    id: "10",
    imageAlt: "Ceramic Plant Pot",
    imageUrl: "/images/item-mock/item10.webp",
    productName: "Ceramic Plant Pot",
    sellerName: "PotteryStudio",
    price: 35.00,
    rating: 4.5,
    isAddedToCart: false,
  },
];

export const mockCategoriesData = [
  "Jewelry",
  "Home Decor",
  "Clothing",
  "Art"
];

export const mockStatusOptionsData = [
    "Active",
    "Draft",
    "Out of Stock"
  ];

export const mockItemDetailsData: ItemDetails =
{
  id: "1",
  name: "Handmade Ceramic Coffee Mug",
  price: 28.0,
  description: "Beautiful handcrafted ceramic coffee mug made with love and attention to detail. Each piece is unique and features a smooth glaze finish. Perfect for your morning coffee or evening tea. Dishwasher and microwave safe.",
  material: "Ceramic",
  capacity: "12 oz",
  dimensions: "4\" x 4\" x 4\"",
  care: "Dishwasher Safe",
  seller: {
    name: "PotteryStudio",
    memberSince: "2019",
    rating: 4.9,
    reviews: 156,
    profileImageUrl: "/images/user_placeholder.png",
  },
  images: [
    "/images/item-mock/item1.webp",
    "/images/item-mock/item2.webp",
    "/images/item-mock/item3.webp",
    "/images/item-mock/item4.webp",
    "/images/item-mock/item5.webp",
    "/images/item-mock/item6.webp",
    "/images/item-mock/item7.webp",
    "/images/item-mock/item8.webp",
    "/images/item-mock/item9.webp",
    "/images/item-mock/item10.webp",
    "/images/item-mock/item11.webp",
    "/images/item-mock/item12.webp",
  ],
  rating: 4.3,
  reviews: 24,
  isAddedToCart: false,
};

export const mockCustomerReviewsData: CustomerReviewsResponse = {
  summary: {
    totalReviews: 24,
    averageRating: 4.3,
    ratingsCount: {
      1: 0,
      2: 0,
      3: 1,
      4: 4,
      5: 19,
    },
  },
  reviews: [
    {
      id: "1",
      reviewerName: "Jane Doe",
      reviewerProfileImageUrl: "/images/user_placeholder.png",
      rating: 5,
      reviewDate: "2 days ago",
      reviewText: "Absolutely love this mug! The craftsmanship is excellent and it feels perfect in my hands. The glaze is beautiful and it keeps my coffee warm. Highly recommend!",
    },
    {
      id: "2",
      reviewerName: "Mike Smith",
      reviewerProfileImageUrl: "/images/user_placeholder.png",
      rating: 5,
      reviewDate: "1 week ago",
      reviewText: "Great quality mug. Arrived quickly and was packaged very well. Perfect size for my morning coffee routine.",
    },
  ],
}

export const mockCartItems: CartItem[] = [
  {
    shoppingItem: {
      id: "1",
      imageAlt: "Handwoven Scarf",
      imageUrl: "/images/item-mock/item1.webp",
      productName: "Handwoven Scarf",
      sellerName: "ArtisanName",
      price: 45.00,
      rating: 4.8,
      isAddedToCart: true,
    },
    quantity: 1,
  },
  {
    shoppingItem: {
      id: "2",
      imageAlt: "Ceramic Mug Set",
      imageUrl: "/images/item-mock/item2.webp",
      productName: "Ceramic Mug Set",
      sellerName: "PotteryMaster",
      price: 32.00,
      rating: 4.9,
      isAddedToCart: true,
    },
    quantity: 2,
  },
  {
    shoppingItem: {
      id: "3",
      imageAlt: "Wooden Jewelry Box",
      imageUrl: "/images/item-mock/item3.webp",
      productName: "Wooden Jewelry Box",
      sellerName: "WoodCrafter",
      price: 78.00,
      rating: 4.7,
      isAddedToCart: true,
    },
    quantity: 1,
  },
];

export const mockQuickStatsData: QuickStatsData = {
  activeProducts: 24,
  avgRating: 4.9,
  totalReviews: 156,
};

export const mockPersonalInfoData: PersonalInfoData = {
  fullName: "Sarah Johnson",
  email: "sarah@potterystudio.com",
  phone: "+1 (555) 123-4567",
  profilePictureUrl: "/images/user_placeholder.png",
};

export const mockInventoryData: InventoryData[] = [
  {
    id: "1",
    name: "Handwoven Scarf",
    description: "A beautiful handwoven scarf made from organic materials.",
    material: "Cotton",
    capacity: "N/A",
    dimensions: "180cm x 30cm",
    care: "Hand wash only",
    seller: {
      name: "ArtisanName",
      memberSince: "2020",
      rating: 4.8,
      reviews: 120,
      profileImageUrl: "/images/user_placeholder.png",
    },
    images: ["/images/item-mock/item1.webp"],
    rating: 4.8,
    reviews: 120,
    isAddedToCart: false,
    stock: 10,
    price: 45.0,
    status: "Active",
    sku: "SCARF001",
    category: "Clothing",
    views: 120,
  },
  {
    id: "2",
    name: "Ceramic Mug Set",
    description: "A set of handcrafted ceramic mugs perfect for any occasion.",
    material: "Ceramic",
    capacity: "300ml",
    dimensions: "10cm x 8cm",
    care: "Dishwasher safe",
    seller: {
      name: "PotteryMaster",
      memberSince: "2018",
      rating: 4.9,
      reviews: 200,
      profileImageUrl: "/images/user_placeholder.png",
    },
    images: ["/images/item-mock/item2.webp"],
    rating: 4.9,
    reviews: 200,
    isAddedToCart: false,
    stock: 5,
    price: 32.0,
    status: "Out of Stock",
    sku: "MUG002",
    category: "Home Decor",
    views: 85,
  },
  {
    id: "3",
    name: "Wooden Jewelry Box",
    description: "A handcrafted wooden jewelry box with intricate carvings.",
    material: "Wood",
    capacity: "N/A",
    dimensions: "20cm x 15cm x 10cm",
    care: "Wipe with a dry cloth",
    seller: {
      name: "WoodCrafter",
      memberSince: "2015",
      rating: 4.7,
      reviews: 150,
      profileImageUrl: "/images/user_placeholder.png",
    },
    images: ["/images/item-mock/item3.webp"],
    rating: 4.7,
    reviews: 150,
    isAddedToCart: true,
    stock: 15,
    price: 78.0,
    status: "Active",
    sku: "JEWELRY003",
    category: "Jewelry",
    views: 150,
  },
  {
    id: "4",
    name: "Knitted Blanket",
    description: "A cozy knitted blanket perfect for chilly evenings.",
    material: "Wool",
    capacity: "N/A",
    dimensions: "200cm x 150cm",
    care: "Machine wash cold",
    seller: {
      name: "YarnArtist",
      memberSince: "2017",
      rating: 5.0,
      reviews: 180,
      profileImageUrl: "/images/user_placeholder.png",
    },
    images: ["/images/item-mock/item4.webp"],
    rating: 5.0,
    reviews: 180,
    isAddedToCart: false,
    stock: 8,
    price: 95.0,
    status: "Active",
    sku: "BLANKET004",
    category: "Home Decor",
    views: 200,
  },
  {
    id: "5",
    name: "Handmade Ceramic Vase",
    description: "A stunning handmade ceramic vase for your floral arrangements.",
    material: "Ceramic",
    capacity: "N/A",
    dimensions: "25cm x 10cm",
    care: "Wipe with a damp cloth",
    seller: {
      name: "ClayArtisan",
      memberSince: "2016",
      rating: 4.6,
      reviews: 140,
      profileImageUrl: "/images/user_placeholder.png",
    },
    images: ["/images/item-mock/item5.webp"],
    rating: 4.6,
    reviews: 140,
    isAddedToCart: false,
    stock: 12,
    price: 50.0,
    status: "Active",
    sku: "VASE005",
    category: "Home Decor",
    views: 110,
  },
  {
    id: "6",
    name: "Woven Basket",
    description: "A durable woven basket for storage or decoration.",
    material: "Natural Fibers",
    capacity: "N/A",
    dimensions: "30cm x 20cm x 15cm",
    care: "Wipe clean with a dry cloth",
    seller: {
      name: "BasketWeaver",
      memberSince: "2021",
      rating: 4.4,
      reviews: 90,
      profileImageUrl: "/images/user_placeholder.png",
    },
    images: ["/images/item-mock/item11.webp"],
    rating: 4.4,
    reviews: 90,
    isAddedToCart: false,
    stock: 20,
    price: 40.0,
    status: "Active",
    sku: "BASKET006",
    category: "Home Decor",
    views: 95,
  },
  {
    id: "7",
    name: "Handcrafted Wooden Bowl",
    description: "A beautifully handcrafted wooden bowl for serving or decoration.",
    material: "Wood",
    capacity: "N/A",
    dimensions: "25cm x 25cm x 10cm",
    care: "Wipe with a dry cloth",
    seller: {
      name: "WoodArtisan",
      memberSince: "2019",
      rating: 4.9,
      reviews: 170,
      profileImageUrl: "/images/user_placeholder.png",
    },
    images: ["/images/item-mock/item12.webp"],
    rating: 4.9,
    reviews: 170,
    isAddedToCart: false,
    stock: 7,
    price: 60.0,
    status: "Active",
    sku: "BOWL007",
    category: "Home Decor",
    views: 130,
  },
  {
    id: "8",
    name: "Embroidered Cushion Cover",
    description: "A vibrant embroidered cushion cover to brighten up your living space.",
    material: "Cotton",
    capacity: "N/A",
    dimensions: "45cm x 45cm",
    care: "Machine wash cold",
    seller: {
      name: "TextileArtist",
      memberSince: "2022",
      rating: 4.7,
      reviews: 100,
      profileImageUrl: "/images/user_placeholder.png",
    },
    images: ["/images/item-mock/item8.webp"],
    rating: 4.7,
    reviews: 100,
    isAddedToCart: false,
    stock: 25,
    price: 25.0,
    status: "Active",
    sku: "CUSHION008",
    category: "Home Decor",
    views: 140,
  },
  {
    id: "9",
    name: "Handmade Leather Wallet",
    description: "A sleek handmade leather wallet with multiple compartments.",
    material: "Leather",
    capacity: "N/A",
    dimensions: "12cm x 10cm",
    care: "Wipe with a damp cloth",
    seller: {
      name: "LeatherCraftsman",
      memberSince: "2014",
      rating: 4.8,
      reviews: 130,
      profileImageUrl: "/images/user_placeholder.png",
    },
    images: ["/images/item-mock/item9.webp"],
    rating: 4.8,
    reviews: 130,
    isAddedToCart: false,
    stock: 18,
    price: 55.0,
    status: "Active",
    sku: "WALLET009",
    category: "Accessories",
    views: 160,
  },
  {
    id: "10",
    name: "Ceramic Plant Pot",
    description: "A charming ceramic plant pot for your indoor plants.",
    material: "Ceramic",
    capacity: "N/A",
    dimensions: "15cm x 15cm",
    care: "Wipe with a damp cloth",
    seller: {
      name: "PotteryStudio",
      memberSince: "2019",
      rating: 4.5,
      reviews: 110,
      profileImageUrl: "/images/user_placeholder.png",
    },
    images: ["/images/item-mock/item10.webp"],
    rating: 4.5,
    reviews: 110,
    isAddedToCart: false,
    stock: 30,
    price: 35.0,
    status: "Active",
    sku: "PLANTPOT010",
    category: "Home Decor",
    views: 125,
  },
];
