export const mockShoppingItemsData = [
  {
    imageAlt: "Handwoven Scarf",
    imageUrl: "/images/placeholder.png",
    productName: "Handwoven Scarf",
    sellerName: "ArtisanName",
    price: "$45.00",
    rating: 4.8,
  },
  {
    imageAlt: "Ceramic Mug Set",
    imageUrl: "/images/placeholder.png",
    productName: "Ceramic Mug Set",
    sellerName: "PotteryMaster",
    price: "$32.00",
    rating: 4.9,
  },
  {
    imageAlt: "Wooden Jewelry Box",
    imageUrl: "/images/placeholder.png",
    productName: "Wooden Jewelry Box",
    sellerName: "WoodCrafter",
    price: "$78.00",
    rating: 4.7,
  },
  {
    imageAlt: "Knitted Blanket",
    imageUrl: "/images/placeholder.png",
    productName: "Knitted Blanket",
    sellerName: "YarnArtist",
    price: "$95.00",
    rating: 5.0,
  },
  {
    imageAlt: "Handmade Ceramic Vase",
    imageUrl: "/images/placeholder.png",
    productName: "Handmade Ceramic Vase",
    sellerName: "ClayArtisan",
    price: "$50.00",
    rating: 4.6,
  },
  {
    imageAlt: "Woven Basket",
    imageUrl: "/images/placeholder.png",
    productName: "Woven Basket",
    sellerName: "BasketWeaver",
    price: "$40.00",
    rating: 4.4,
  },
  {
    imageAlt: "Handcrafted Wooden Bowl",
    imageUrl: "/images/placeholder.png",
    productName: "Handcrafted Wooden Bowl",
    sellerName: "WoodArtisan",
    price: "$60.00",
    rating: 4.9,
  },
  {
    imageAlt: "Embroidered Cushion Cover",
    imageUrl: "/images/placeholder.png",
    productName: "Embroidered Cushion Cover",
    sellerName: "TextileArtist",
    price: "$25.00",
    rating: 4.7,
  },
  {
    imageAlt: "Handmade Leather Wallet",
    imageUrl: "/images/placeholder.png",
    productName: "Handmade Leather Wallet",
    sellerName: "LeatherCraftsman",
    price: "$55.00",
    rating: 4.8,
  },
  {
    imageAlt: "Ceramic Plant Pot",
    imageUrl: "/images/placeholder.png",
    productName: "Ceramic Plant Pot",
    sellerName: "PotteryStudio",
    price: "$35.00",
    rating: 4.5,
  },
];

export const mockCategoriesData = [
  "Jewelry",
  "Home Decor",
  "Clothing",
  "Art"
];
